name: "Deploy on server"

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Set up SSH"
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Deploy to AWS instance"
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.195.43.115 << 'EOF'
            cd /home/ubuntu/server/nodeapp  # Fixed directory name typo
            git pull origin main
            # Ensure the node process is properly managed, e.g., using pm2
            pm2 restart app || pm2 start app.js --name "app"
          EOF
